thread_numbers: 3
debug_info: false
delay_mode: false
#最大速度
mpc_max_vel: 0.5
mpc_max_angvel: 0.8
mpc_max_jntvel: 0.5
#控制频率
controller_freq: 1
_dt: 0.1
#pid到初始位姿频率
pid_freq: 10
#urdf——file 这个就先不填了，cpp里有写
mpc_freq_int: 10

#需要增加的重复轨迹长度
increase_length: 166 #int #这个必须小于最近的mpc_step的倍数
#mpc的预测范围/时间步长
mpc_steps: 35 #int

delay_steps: 6
#mpc的目标函数的各项权重
#运动学
mpc_w_distx: 100000.0 # 50.0
mpc_w_disty: 100000.0 # 50.0
mpc_w_etheta: 4500000.0 # 50.0
mpc_w_jnt: 10000000.0 # 50.0
mpc_w_jnt2: 100000000000.0 # 10000 times

mpc_w_vel: 2.0
mpc_w_angvel: 5.0
mpc_w_jntvel: 1.0

mpc_w_acc: 10.0 # 100.0
mpc_w_angacc: 10.0 # 100.0
mpc_w_jntacc: 100.0 # 100.0
#碰撞
collision_base_weight: 150000.0 # 200 #1/3 #right up/left down 0.5
collision_shoulder_weight: 5000.0 # 100 #0.5
collision_elbow_weight: 5000.0 # 100 #0.5
collision_wrist_weight: 20000.0 # 100 #0.5 #right down 1
collision_gripper_weight: 50000.0 # 100 #0.5 #right down 1.5 #left down 2.5
#碰撞的阈值
base_threshold: 0.8 #0.4 urdf
shoulder_threshold: 0.3 #0.15 urdf
elbow_threshold: 0.3 #0.15 urdf
wrist_threshold: 0.3 #0.15 urdf
gripper_threshold: 0.3 #0.15 urdf
#行人的参数
pedestrian_threshold: 0.5 # 0.2 urdf
pedestrian_velocity_x: 0.024
#0 #0 #-0.019 #0.0225 #-0.024 #0.024
pedestrian_velocity_y: -0.079
#-0.11 #-0.088 #-0.055 #0.0615 #0.056 #-0.079

#对于惩罚函数 barried function
barried_arm_n: 0.2 # 1.0
barried_arm_w: 10.0
barried_arm_m: 4.7 #3.5
barried_arm_r: -0.2 # 1.0

barried_base_n: 1.0
barried_base_w: 10.0
barried_base_m: 4.7 #3.5
barried_base_r: 0.0 #1.0

#终端约束，即tool的最终在world下的xyzrpy
ee_tool_x: 1.0 #1.21 #1.35
ee_tool_y: 0.55 #0.56 #0.5675
ee_tool_z: 1.1365 #1.1365
ee_tool_roll: 0.0
ee_tool_pitch: 0.0
ee_tool_yaw: 0.0
#终端约束为hard constrain，权重加大
terminal_weight_infite: 50000000000000000000000000000000.0

#ur5e的关节角度限制, urdf中看到
joint1_upper_bound: 3.14
joint1_lower_bound: -3.14
joint2_upper_bound: 3.14
joint2_lower_bound: -3.14
joint3_upper_bound: 3.14
joint3_lower_bound: -3.14
joint4_upper_bound: 3.140.6
joint4_lower_bound: -3.14
joint5_upper_bound: 3.14
joint5_lower_bound: -3.14
joint6_upper_bound: 3.14
joint6_lower_bound: -3.14

#到达初始位姿的pid
x_kp: 0.2
x_ki: 0.01
x_kd: 0.005

y_kp: 0.2
y_ki: 0.01
y_kd: 0.005

yaw_kp: 0.2
yaw_ki: 0.01
yaw_kd: 0.005
#到达初始位姿的容差
tolerance_position: 0.05
tolerance_theta: 0.10
tolerance_joint: 0.08 #0.01 for 0.5度

savefolder_path: "/home/diamondlee/VKConTieta_ws/src/tieta_mpc_sim_demo/tieta_result_csv/result"
save_Debugfolder_path: "/home/diamondlee/VKConTieta_ws/src/tieta_mpc_sim_demo/tieta_result_csv/debug"
