thread_numbers: 3
debug_info: false
delay_mode: false
#最大速度
mpc_max_vel: 0.5
mpc_max_angvel: 0.8
mpc_max_jntvel: 0.5
#控制频率
control_freq: 10
#pid到初始位姿频率
pid_freq: 10
#urdf——file 这个就先不填了，cpp里有写

#mpc的预测范围/时间步长
mpc_steps: 10
#mpc的目标函数的各项权重
#运动学
mpc_w_distx: 50
mpc_w_disty: 50
mpc_w_etheta: 50
mpc_w_vel: 100
mpc_w_angvel: 100
mpc_w_jnt: 50
mpc_w_jntvel: 100
#碰撞
collision_base_weight: 1000000
collision_shoulder_weight: 1000
collision_elbow_weight: 1000
collision_wrist_weight: 1000
collision_gripper_weight: 1000
#碰撞的阈值
base_threshold: 1.0
shoulder_threshold: 0.05
elbow_threshold: 0.05
wrist_threshold: 0.05
gripper_threshold: 0.05
#行人的参数
pedestrian_threshold: 0.5
pedestrian_velocity: 0.00

#终端约束，即tool的最终在world下的xyzrpy
ee_tool_x: 0.0
ee_tool_y: 0.0
ee_tool_z: 0.0
ee_tool_roll: 0.0
ee_tool_pitch: 0.0
ee_tool_yaw: 0.0
#终端约束为hard constrain，权重加大
terminal_weight_infite: 50000

#ur5e的关节角度限制, urdf中看到
joint1_upper_bound: 3.14
joint1_lower_bound: -3.14
joint2_upper_bound: 3.14
joint2_lower_bound: -3.14
joint3_upper_bound: 3.14
joint3_lower_bound: -3.14
joint4_upper_bound: 3.14
joint4_lower_bound: -3.14
joint5_upper_bound: 3.14
joint5_lower_bound: -3.14
joint6_upper_bound: 3.14
joint6_lower_bound: -3.14

#到达初始位姿的pid
x_kp: 0.2
x_ki: 0.01
x_kd: 0.005

y_kp: 0.2
y_ki: 0.01
y_kd: 0.005

yaw_kp: 0.2
yaw_ki: 0.01
yaw_kd: 0.005
#到达初始位姿的容差
tolerance_position: 0.01
tolerance_theta: 0.01
tolerance_joint: 0.01 #0.5度

savefolder_path: "/home/diamondlee/VKConTieta_ws/src/tieta_mpc_sim_demo/tieta_result_csv/result"
save_Debugfolder_path: "/home/diamondlee/VKConTieta_ws/src/tieta_mpc_sim_demo/tieta_result_csv/debug"
